# Generated by Django 3.2.12 on 2022-03-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Unit_Number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Mileage', models.PositiveIntegerField(default=0)),
                ('Manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('Status', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'db_table': 'VEHICLE',
            },
        ),
        migrations.CreateModel(
            name='MileageRecords',
            fields=[
                ('Record_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Record_Date', models.DateField()),
                ('Mileage', models.PositiveIntegerField(default=0)),
                ('Unit_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_app.vehicle')),
            ],
            options={
                'db_table': 'MILEAGE_RECORDS',
                'unique_together': {('Unit_Number', 'Record_Date')},
            },
        ),
    ]
